### ISSUE TITLE
Does not work with VSC Remote SSH

### ISSUE THREAD

**Issue by JtMotoX** [RapidAPI/feedback#10]
I do all my development on remote machines (Linux VM's).  I was looking forward to trying this extension after coming across a youtube video on it.

This extension does not work with [Visual Studio Code Remote SSH](https://code.visualstudio.com/docs/remote/ssh), [Visual Studio Code Server](https://code.visualstudio.com/blogs/2022/07/07/vscode-server), or [coder/code-server](https://github.com/coder/code-server).  It just shows a spinning when you try to launch this extension.

![image](https://user-images.githubusercontent.com/7191259/181877827-fc4ade1e-6423-4e8d-a28c-295389f8217f.png)

**Comment by estruyf** [comment]
Thanks, @JtMotoX this has probably to do with the extension relying on some Node processes. Our first focus was to get it released for standard VS Code use-cases. This was not yet one of them. 

We will add this to our backlog to investigate and see how we can make it work for these remote machines.

**Comment by estruyf** [comment]
We will make a change to make sure the extension is installed locally instead of on the remote.

**Comment by estruyf** [comment]
With the v1.2.0 release, the extension will require installing it on the local instance instead of the remote one. This should fix the issue.
