### ISSUE TITLE
[Bug]: GET requests with body don't work even when the setting is enabled

### ISSUE THREAD

**Issue by haiowin** [RapidAPI/feedback#102]
### What happened?

I was trying to make a GET request with a body in localhost, and I have the "send request body in all request types" setting enabled both in user and workspace. 

The expected result would be that the request is successfully made, but the body isn't actually sent.

### Steps to reproduce?

1. Write a basic endpoint that accepts a GET request with a body.
2. Send the request using RapidAPI extension.
3. You can check that the body is not sent.

### VS Code version

1.76.0

### Extension version

1.9.3

**Comment by estruyf** [comment]
We are going to remove support for this and just warn you to switch to a POST request, as this is against the standards of HTTP.

https://fetch.spec.whatwg.org/#dom-request - check step 35

![Xnapper-2023-03-16-17 03 58](https://user-images.githubusercontent.com/2900833/225680579-4ad2d4c0-8fa9-4cc4-9849-72b72dfa7d06.png)

**Comment by estruyf** [comment]
We've removed this functionality to comply with the standard. Thank you @haiowin for reporting this! 🙏
