### ISSUE TITLE
[Bug]: Can't copy content on the Response Web view

### ISSUE THREAD

**Issue by dxkrs** [RapidAPI/feedback#104]
### What happened?

On the Response -> Web view, copy not work even command+c or right click. The other view such as Headers or Text is OK.
Is it a bug? I want the copy can work in the Web view when I coding and testing.

### VS Code version

1.76.2

### Extension version

1.9.3

**Comment by ststimac** [comment]
@dxkrs thanks for reporting this, I'll take it back to the team. This functionality is available in our web and mac applications so I would expect it to be in VS Code too but am unsure if there are limitations I'm not aware of. Thanks!

**Comment by ststimac** [comment]
@dxkrs Following up here, unfortunately the WebView in VS Code has restrictions which means some actions aren't available and those include copy + paste functionality.
