### ISSUE TITLE
does not work without a network

### ISSUE THREAD

**Issue by RomanMaronov** [RapidAPI/feedback#14]
Hi!
My working environment is in the internal contour of the company. There is no internet access.
I keep getting messages:
```
["INFO" - 2022-08-01T07:52:52.017Z - v1.0.3]
   Proxy fetch ERROR: "AbortController is not defined"
```

Can RapidAPI Client work without network access?

**Comment by estruyf** [comment]
The extension should be able to call internal APIs without needing an internet connection. The error you posted is for the timeout and canceling of the API calls. 

You can try to turn on `verbose` logging with the `rapidapi.logging.level` setting and see what the API response was for the local calls.

**Comment by RomanMaronov** [comment]
`["INFO" - 2022-08-01T08:41:01.820Z - v1.0.3] 
  [request-updates]: no data provided
["VERBOSE" - 2022-08-01T08:41:02.284Z - v1.0.3] 
  Proxy fetch: https://www.google.com/ - GET - [] - {"requestUuid":"6e994638-9fab-42ec-97b2-e00cebe0a66e","projectUuid":"vscode-generator","libName":"RapidAPI - VS Code","request":{"method":"GET","url":"https://www.google.com/","params":{},"headers":{},"bodyType":"text","data":""}}
["INFO" - 2022-08-01T08:41:02.284Z - v1.0.3] 
  Proxy fetch ERROR: "AbortController is not defined"
["VERBOSE" - 2022-08-01T08:41:02.285Z - v1.0.3] 
  RapidAPI Client started: 31`

**Comment by estruyf** [comment]
Which version of VS Code are you using @RomanMaronov?

**Comment by RomanMaronov** [comment]
ver: 1.65.2
Node: 14.16.0
OS: win10

**Comment by estruyf** [comment]
Thanks, this information helped a lot!

Seems that the minimal version of VS Code should be bumped to `>1.66.x`.

**Comment by RomanMaronov** [comment]
Thanks!
Installed 1.69.2, everything worked

**Comment by estruyf** [comment]
I will update the minimal version for the extension right now. Thanks for your help @RomanMaronov 🙏.
