### ISSUE TITLE
[Enhancement]: Better Cookie Interaction

### ISSUE THREAD

**Issue by tjwells85** [RapidAPI/feedback#19]
### What do you think of the extension?

I really like this extension a lot, but one area I am having an issue with is cookies.  A lot of the APIs I develop use cookie-based authentication, and it seems a bit cumbersome to use them here.  I have to log in, get a cookie, and then in the header for each subsequent request add the cookie manually.  Would be nice if there was a project-level cookie store and all requests in that project will automatically include those cookies.

**Comment by estruyf** [comment]
Thanks, @tjwells85 this is on the roadmap. We currently have this in our Studio (web) experience. We are doing some design work to make it fit in the VS Code extension.

**Comment by ozguncagri** [comment]
This is the only reason to uninstall it right away and really big deal breaker for me. Thunder client does the same thing and that's why I'm not using it either. We need proper cookie manager that works just like in insomnia or postman. Please prioritize this feature.

**Comment by estruyf** [comment]
Let us keep this issue open until this functionality is implemented.

Thanks, @ozguncagri. We will have it, as both our macOS app (https://paw.cloud/) and web experience have it.

**Comment by Wilmela** [comment]
Great extension. Really saves the stress of switching screens. However, the area of managing cookies, has been my concern but i will wait to see the changes you will make in the future. Thanks a lot.

**Comment by then3rdman** [comment]
Adding to the need for cookies. ONly thing stopping me from switching to this extesntion.

**Comment by mp54214** [comment]
Yes, same here, otherwise very great extension, but the lack of cookie management support stopped me using it so far. Please, try to implement it, and then I will return to its usage!

**Comment by estruyf** [comment]
@mp54214 good news, the cookies have been implemented, and we are currently internally testing it before we launch it.

**Comment by mp54214** [comment]
> @mp54214 good news, the cookies have been implemented, and we are currently internally testing it before we launch it.

Great to hear, let us just know when launched - well done!

**Comment by Wilmela** [comment]
> @mp54214 good news, the cookies have been implemented, and we are currently internally testing it before we launch it.

Great! Way to go! . Well done to the team.

**Comment by estruyf** [comment]
Version 1.7.0 just got released with session/cookie support for requests.

**Comment by mp54214** [comment]
...just tested it and seems to work as expected, cookies to be seen on response headers, great!
