### ISSUE TITLE
[Bug]:  Connection Request Failed with OctoPaw

### ISSUE THREAD

**Issue by deepraj02** [RapidAPI/feedback#20]
### What happened?

Unable to SignIn with OctoPa
![pic](https://user-images.githubusercontent.com/63138398/182339538-a41fc7d2-0a50-499b-a7da-9a0e1b8ca1b5.png)
![pic2](https://user-images.githubusercontent.com/63138398/182339545-01d6e440-93fd-4a1c-9cf0-e17c0c649a64.png)

### Steps to reproduce?

![pic2](https://user-images.githubusercontent.com/63138398/182339571-6acd0f8c-a0cd-4245-abcd-d89c2b4eb0f8.png)
![pic](https://user-images.githubusercontent.com/63138398/182339575-7641a4d6-1daa-43e1-86f3-82682df18f45.png)

### VS Code version

Code Insiders 1.70.0

### Extension version

v 1.1.0

**Comment by estruyf** [comment]
Thanks @deepraj02, this issue was already reported #5. Currently, we only support the main version of VS Code, not yet the insider version.
