### ISSUE TITLE
[feedback]: Authorization tab doesn't exist in request groups

### ISSUE THREAD

**Issue by ehsanbigzad** [RapidAPI/feedback#24]
### What do you think of the extension?

A big thanks to the developers who put their time and made this addon.

- Bearer token method doesn't exist in authorization tab.
- Request groups doesn't accept headers or authorization methods
- Dropdowns doesn't work smoothly.

**Comment by estruyf** [comment]
Thanks @ehsanbigzad for opening this issue.

> Bearer token method doesn't exist in authorization tab.

Bearer token is on its way to be added in the auth option

> Request groups doesn't accept headers or authorization methods

Groups are just a sort of container which can hold requests. There are no settings you can set on these groups.

> Dropdowns doesn't work smoothly.

Would you be able to show what exactly you mean with this?
