### ISSUE TITLE
[Help]: How can I use Env variables ? like BASE_URL ??

### ISSUE THREAD

**Issue by ruhankhandakar** [RapidAPI/feedback#25]
### What do you think of the extension?

Thanks for this pretty awesome extension,

**Comment by estruyf** [comment]
@ruhankhandakar thank you for the feedback 🙏. If you want to use environment variables, start by typing `{` in the input and select **Environment Variable**. Once you selected that, you can click on it and select the environment variable you want to use.

![Xnapper-2022-08-03-18 55 39](https://user-images.githubusercontent.com/2900833/182665734-bfda2bc5-5f94-42a7-8893-cf2d9c156132.png)

**Comment by ruhankhandakar** [comment]
Awesome, Thanks :D
