### ISSUE TITLE
[Bug]: Incorrect Basic Auth Token Generated

### ISSUE THREAD

**Issue by satyamdalai** [RapidAPI/feedback#26]
### What happened?

If we try to use basic auth for any api, the token generated and passed as the header is incorrect.

### DebugBear
![debugbear](https://user-images.githubusercontent.com/54313146/182629604-d77eb9a8-bf20-4eea-8176-ed9bb3dc509f.png)

### RapidAPI Client
![rapidAPI Client](https://user-images.githubusercontent.com/54313146/182629728-3f4c1671-df45-4628-91b0-0df931454023.png)

### Steps to reproduce?

1. Create any sample request.
2. Click on the auth tab and select Basic
3. Give username and password as admin and admin@123
4. Go back to headers tab and check the token generated and make a note.
5. Visit [DebugBear](https://www.debugbear.com/basic-auth-header-generator), and put the same creds and you can find the token generated from the rapid API client is wrong.

### VS Code version

1.69.2

### Extension version

1.1.0

**Comment by estruyf** [comment]
Thank you, @satyamdalai. I've verified this, and it seems to indeed be an issue on our end and will be fixed.

**Comment by satyamdalai** [comment]
Looks like issue fixed in the extension version 1.3.0, hence closing the issue.
Thanks @estruyf and all the best with 👍🏽

**Comment by estruyf** [comment]
Thanks @satyamdalai for verifying this!
