### ISSUE TITLE
[Bug]: fresh install received error opening default "Request 1"

### ISSUE THREAD

**Issue by ovruch** [RapidAPI/feedback#27]
### What happened?

Fresh install. Clicked on default "Request 1" to see details and received an error:
You have encountered an error
Error: Illegal value for token color: #B4DB
Event ID: 1b28847a93e949abaf82cb56e5c4c911

### Steps to reproduce?

Install, open default request

### VS Code version

1.69.2

### Extension version

v1.1.0

**Comment by estruyf** [comment]
Thanks, @ovruch. This seems to be an issue translating the VS Code theme to the Monaco editor. Unfortunately, they don't map 1-to-1.

Would you mind sharing your theme so we can test it out?

**Comment by ovruch** [comment]
VS Them used Pop N' Lock Theme by Luxcium v3.32.7

**Comment by estruyf** [comment]
Thanks, I'll get it tested right away and come with a fix.

**Comment by estruyf** [comment]
Verified, and the theme contains invalid HEX color values `#B4DB` - a hex value should be three, six, or eight characters, not four. Fix for this is coming.

**Comment by estruyf** [comment]
This should have been fixed in version `1.2.0`.

**Comment by juarinu** [comment]
I had the same error with "IntelliJ-ish Darcula" theme (with color value red). I have now "Cobalt2" with no errors.
