### ISSUE TITLE
[feedback]: How do I learn about what Telemetry you collect and how can I disable it if I want?

### ISSUE THREAD

**Issue by danawoodman** [RapidAPI/feedback#28]
### What do you think of the extension?

An API client such as RapidAPI Client could be privy to private keys and other sensitive information. 

The telemetry you collect needs to be made explicit to users. I've reviewed the privacy policy but I don't see details. I would like to know if you are tracking things like requests made, env keys, errors or any other type of input/output that the client is privy to that could contain sensitive information.

In addition, I do not see any way to opt out of telemetry. How can someone opt out of telemetry?

**Comment by ststimac** [comment]
Hi @danawoodman, when it comes to the telemetry we are able to see events triggered, but not the content of those events. So for example in VS Code, we know when the extension is loaded, if a project is selected or created, when a request panel is open, and when a request is sent, what theme is being used and when someone signs out or into the RapidAPI service. 

In our telemetry data we can't see the content of requests, env keys or input/output data.

If you've signed into VS Code with your RapidAPI account, then we have your email but if you haven't signed in then the telemetry data shows a randomly generated ID. Whether you've signed in or not doesn't affect the telemetry data either, we can still only see the events that were fired, not the content of those events. 

For VS Code, we still need to implement some code on our side, but the current plan is that if you've opted out of telemetry in VS Code we won't track. If you've logged in and want to opt out, we can remove you from the telemetry data.

**Comment by danawoodman** [comment]
Thanks for the details 👍
