### ISSUE TITLE
Add option to skip login with OctoPaw

### ISSUE THREAD

**Issue by ttsirkia** [RapidAPI/feedback#3]
It seems that if the user does not log in, the profile icon will always show the badge "1"

![kuva](https://user-images.githubusercontent.com/2797729/181366576-6efb6ec3-bfcd-4155-b182-2d397464e500.png)

Could there be an option to skip this?

**Comment by estruyf** [comment]
Thank you, @ttsirkia, for testing out the extension. This is the default behavior of VS Code when we register our Auth Provider for RapidAPI.

**Comment by mkrohn** [comment]
I would like to add, the sign-in icon is the same as sign-out icon, even the same color.

**Comment by estruyf** [comment]
@mkrohn, the sign-in and sign-out actions use the VS Code icons. There is a slight difference in both:

![Xnapper-2022-08-30-13 31 27](https://user-images.githubusercontent.com/2900833/187425874-153f4484-a436-4911-a5ea-8d14e1420be3.png)

- Top: user is signed in -> the sign-out icon is shown
- Bottom: user is signed out -> the sign-in icon is shown

**Comment by estruyf** [comment]
We improved this experience in version `1.5.0`, which just got released.
