### ISSUE TITLE
[Bug]: Authentication Fails.

### ISSUE THREAD

**Issue by FattyMango** [RapidAPI/feedback#33]
### What happened?

Hi, 
I'm using Laravel 9 trying out Token Authentication, when I pass the Bearer and the token, RapidAPI exclude an important character in Sanctum tokens. 
For example:
it must be : 
`Bearer 5|ZNDi5LnPM5rIx5mqGUfoGvnFnVrPYc9dhYmWGfLo`
but RapidAPI changes it to:
`Bearer 5ZNDi5LnPM5rIx5mqGUfoGvnFnVrPYc9dhYmWGfLo`
it excludes `|`.

ps: it works fine using Postman

### Steps to reproduce?

I think it just needs to keep it as it is without changing the token.

### VS Code version

1.69

### Extension version

v1.3.0

**Comment by estruyf** [comment]
Thanks @FattyMango we'll investigate the issue.

**Comment by estruyf** [comment]
The issue got fixed in version `1.4.0`.
