### ISSUE TITLE
[feedback]: file upload issue

### ISSUE THREAD

**Issue by NA-Siddiky** [RapidAPI/feedback#39]
### What would you like to tell us?

if we want to post of file like an image or pdf to the server there is a problem.

**Comment by estruyf** [comment]
Thanks @NA-Siddiky for reporting this. Issue was already opened, so will link this issue to it can close it.

Duplicate: #31

**Comment by NA-Siddiky** [comment]
thanks for your attention and nice cooperation. if you need any information or any kinds of support from me don't hesitate to connect me.
