### ISSUE TITLE
Add support to import curl

### ISSUE THREAD

**Issue by mainendra** [RapidAPI/feedback#4]
It's easy to copy curl command used in any web application using chrome dev tools.
So, it will be really helpful to import that curl and create a request that we can test.

**Comment by estruyf** [comment]
@mainendra great news! Single curl requests are supported to be imported. All you have to do is run the `RapidAPI: Create new request from clipboard` command in VS Code.

**Comment by mainendra** [comment]
Thanks @estruyf
