### ISSUE TITLE
[Bug]: Name of the Request keep changing back to default when setting the name in Name Field

### ISSUE THREAD

**Issue by TheValkDokk** [RapidAPI/feedback#42]
### What happened?

When setting the Name of the Request using Name Field in Description Tab, others Request Name will be set back to the default Request 1,2,3,4,...

### Steps to reproduce?

Set Name using Name Field in Description Field of the first Request, the name on the list of request panel on the left will be updated.
Set Name using Name Field in Description Field on the second Request, the name of this second request will be update, BUT others Request name will be change back to the default Request 1, 2, 3 ,4, etc. The value in the Name Field of those changed Request will stay the same

### VS Code version

1.7

### Extension version

1.4

**Comment by ststimac** [comment]
Hi @TheValkDokk, are you still having this issues with extension version 1.4.1? I'm currently unable to reproduce this. 

If this is still happening, how are you adding new requests? With the "+" button next to the Requests header in the sidebar? Or by selecting the three dots next to a request name?

**Comment by TheValkDokk** [comment]
I'm using the '+' button
