### ISSUE TITLE
[feedback]: fullscreen

### ISSUE THREAD

**Issue by luisArthurRodriguesDaSilva** [RapidAPI/feedback#45]
### What would you like to tell us?

this extension is good but i cant use the right side on fullscreen mode to have a easyer vision of the responses

**Comment by ststimac** [comment]
@luisArthurRodriguesDaSilva can you elaborate? Is the right side unresponsive when trying to use it in fullscreen mode?

**Comment by luisArthurRodriguesDaSilva** [comment]
viewing a big response is not easy because it is too small, if it had a fullscreen mode that the left and the top side are hidden, the vision would be better;
![image](https://user-images.githubusercontent.com/66787949/185475779-01bd8354-9afa-40d1-8997-adc717358b6e.png)
![WhatsApp Image 2022-08-18 at 16 23 25](https://user-images.githubusercontent.com/66787949/185477783-1038c6c1-9e61-48b6-a906-5b44b7a3a7af.jpeg)

**Comment by ststimac** [comment]
@luisArthurRodriguesDaSilva understood, thank you!

**Comment by estruyf** [comment]
We added the functionality to toggle a full-screen mode in the latest 1.5.0 release.

![Xnapper-2022-09-02-09 05 15](https://user-images.githubusercontent.com/2900833/188169192-10fbc745-5a11-487c-955e-ba177ea19678.png)
