### ISSUE TITLE
[feedback]: Sync constantly overrides what I'm doing

### ISSUE THREAD

**Issue by vieraleonel** [RapidAPI/feedback#50]
### What would you like to tell us?

Sync is constantly overriding what I'm doing, to de point that it may even override several request changes.

For example.
1. I'm creating a 4 requests for a typical CRUD API
2. After creating the CREATE request, I duplicate the endpoint to make the UPDATE request
3. I copy CREATE's request body to reuse it for UPDATE request.
4. After I paste it in UPDATE request's body, I start changing it and suddenly the textarea refresh and I loose all the modifications.

Sometimes it even overrides the request name, query params, headers or any change I make.

I get to the point where I'm always paying attention to the `syncing...` indicator in status bar in order not to loose my progress; I'm waiting for it to finish before I make any change.

Maybe a simple solution would be the ability to sync/push changes manually with `Crl/Cmd + S` or a button to sync manually (perhaps a configuration of the plugin?)

**Comment by estruyf** [comment]
@vieraleonel sorry to hear this is happening. Would you be able to share the experience with us via recording?

**Comment by zuisong** [comment]
It happens to me too

**Comment by estruyf** [comment]
In version 1.5.0, we improved the syncing behavior. Let us know if you still keep experiencing it.
