### ISSUE TITLE
[feedback]: Too many notifications

### ISSUE THREAD

**Issue by wottpal** [RapidAPI/feedback#51]
### What would you like to tell us?

I like the extension but it definitely needs a silent mode. Too many unnecessary notifications disturb me in my flow state. Thinking about removing it after all...

**Comment by ststimac** [comment]
Thanks for your feedback @wottpal, are there specific notifications you're getting too often or just all of them?

**Comment by wottpal** [comment]
Can't remind exactly (maybe something about an API key or login or so?). Already removed it. There should be at least a "Don't show this type of notification again" button. I think I've seen this for other notifications in VSCode before.

**Comment by wottpal** [comment]
<img width="455" alt="Screen Shot 2022-08-26 at 12 56 19" src="https://user-images.githubusercontent.com/3930150/186889086-95a872ad-b00f-4842-8db8-339766fa8b0c.png">

**Comment by estruyf** [comment]
@wottpal @mohammad-naimur-rahman in the latest hotfix release, the notifications have been turned off.
