### ISSUE TITLE
[feedback]: Implement to Disable SSL verification

### ISSUE THREAD

**Issue by bognarbalazs** [RapidAPI/feedback#55]
### What would you like to tell us?

I use RapidAPI client in the VSCode and it's a cool tool, but it'd be nice if i could disable the SSL verification sometime.

**Comment by estruyf** [comment]
In version 1.9.0, which will be out in a couple of minutes, there is a new setting to enable/disable SSL verification. The setting is called: `rapidapi.ssl.verification`.
