### ISSUE TITLE
[feedback]: Option to disable timeout

### ISSUE THREAD

**Issue by ChrisAcrobat** [RapidAPI/feedback#60]
### What would you like to tell us?

Right now we can define a timeout threshold, but it seams not to accept very large or zero/negative numbers*.
I would like to be able to disable the timeout drop, because sometimes I am working with very slow API:s.
A great compromise would be a warning popup or something instead, so we still get notified when a API call take to long time: Just do not drop it.

Other then that, great work on the extension! 🥇

\* It accepts them, but do fall back to default.

**Comment by estruyf** [comment]
In version 1.5.0, you can now set the value to `0` or `-1` to disable it.
