### ISSUE TITLE
[Bug]: some curl request import result is not correct

### ISSUE THREAD

**Issue by zuisong** [RapidAPI/feedback#61]
### What happened?

import curl not correct

### Steps to reproduce?

```shell
curl 'https://httpbin.org/anything' \
  -H 'content-type: application/json;charset=UTF-8' \
  --data-raw '{"a":1}' \
  --compressed
```

1. import to RapidAPI
2. The result is a get request and lost request body. Actually, it is a post request

### VS Code version

1.70.2

### Extension version

1.4.2

**Comment by estruyf** [comment]
Thanks @zuisong for opening an issue for this. We'll fix it in the upcoming release.

**Comment by estruyf** [comment]
We just released a new version in which this issue should be fixed.
