### ISSUE TITLE
[Bug]: Fetching old url

### ISSUE THREAD

**Issue by duckimann** [RapidAPI/feedback#66]
### What happened?

The extension fetching the old url (when use the Ctrl + Enter keystroke)

### Steps to reproduce?

[Video](https://imgur.com/a/HLqFPTC)

### VS Code version

1.71.0

### Extension version

1.6.0

**Comment by estruyf** [comment]
This issue is fixed in our latest release. Thanks again @duckimann for opening an issue 🙏
