### ISSUE TITLE
Cannot use "Publish to github" while extension is active

### ISSUE THREAD

**Issue by MightyCoderX** [RapidAPI/feedback#73]
Type: <b>Bug</b>

- Have a folder open
- Have RapidAPI extension
- Click on source control menu item on the primary sidebar
- Click on "Publish To Github" / "Publish Branch"

After that button is clicked the dialog opens then closes instantly

Extension version: 1.6.0
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.55GB free)|
|Process Argv|--crash-reporter-id 248870e0-cac7-4a8d-a18e-a3664f313ada|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by Theakayuki** [comment]
Can confirm went thru all my extentions to find it was rapidAPI that was doing it.

**Comment by estruyf** [comment]
@Theakayuki, why do you think that this is related? The extension does not have any connection with the source control experience from VS Code. Also, the error you link to comes from the web view, which is not running on the extension level from VS Code. Feel free to share if you have more information or why it is related.

**Comment by estruyf** [comment]
The 1.7.0 release fixes this issue, so you should be able to use GitHub functionalities again.
