### ISSUE TITLE
[Bug]: Add environment group button is not working

### ISSUE THREAD

**Issue by JuanPabloOS** [RapidAPI/feedback#74]
### What happened?

I deleted my default group in the environments section and after that I wasn't able to add a new one

### Steps to reproduce?

- open the RapidAPI extension
- on the Environments section delete all of your groups (I just had the default group)
- An empty state is shown with the label "No environment groups yet" and a "Add environment Group" button 
- if you click the button it does nothing, so you are not able to create a new group

### VS Code version

1.73.0

### Extension version

1.7.0

**Comment by estruyf** [comment]
Thanks @JuanPabloOS, we've been able to reproduce it and will release a fix for this tomorrow.

**Comment by estruyf** [comment]
This issue is fixed in our latest release. Thanks again @JuanPabloOS for opening an issue 🙏
