### ISSUE TITLE
[feedback]: Link handle Dialog

### ISSUE THREAD

**Issue by Negan1911** [RapidAPI/feedback#76]
### What would you like to tell us?

Hey folks, great extension, just a minor detail.

Can we put a setting to disable the "How would you like to handle the link?" dialog? 99% of the time I just want to follow the link and not create a request with it, it would be great if at least there's something that I can put on the `settings.json` to disable it, something like:
```
"rapidApi.clicked_link_dialog": "defaultNavigate"
```

Will be really appreciated!

**Comment by estruyf** [comment]
@Negan1911 thank you for the feedback and for opening an issue around this. 

The link handler is, by default, disabled, it could be that you accidentally enabled it by clicking on a notification. To turn off the experience, you can set the `rapidapi.terminalLink.enabled` in your user settings to `null`.

**Comment by Negan1911** [comment]
Yup, that's true, thank you!
