### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by grhughes** [RapidAPI/feedback#8]
Installed RapidAPI into VSCode and tried a simple get to an open API.  I get No Response.  The line works find in Chrome.
Debug logging shows.
["VERBOSE" - 2022-07-29T19:08:13.759Z - v1.0.3] 
  Proxy fetch: https://catfact.ninja/fact - GET - [] - {"requestUuid":"f3594578-3da0-4d63-9a03-8977c705869e","projectUuid":"vscode-generator","libName":"RapidAPI - VS Code","request":{"method":"GET","url":"https://catfact.ninja/fact","params":{},"headers":{},"bodyType":"text","data":""}}
["INFO" - 2022-07-29T19:08:13.759Z - v1.0.3] 
  Proxy fetch ERROR: "AbortController is not defined"
["VERBOSE" - 2022-07-29T19:08:13.759Z - v1.0.3] 
  RapidAPI Client started: 151

**Comment by grhughes** [comment]
Ok, figured it out.  I needed to update VSCode to the latest release and it's now working.  Sorry for the false alarm.

**Comment by estruyf** [comment]
Thanks @grhughes good to know that VS Code updates can block the calls.
