### ISSUE TITLE
No response on localhost

### ISSUE THREAD

**Issue by franklin-vidal** [RapidAPI/feedback#82]
Hi,

A request to rails application on localhost:3000(Fedora linux) return "No response". I'm tryed to used 127.0.0.1:3000 and get the same error.

Thanks for help.

**Comment by ManuLpz4** [comment]
Same here

**Comment by ARSHADKHAN615** [comment]
Same here @franklin-vidal any news about this?

**Comment by RmK9** [comment]
Can confirm as well that the 1.9.0 version is indeed bugged and downgrading as per @ManuLpz4 solved it for me as well.

**Comment by wilsoft-gt** [comment]
same issue for me, in my case I'm getting this error when using it from my django localserver:

`[03/Jan/2023 16:27:44] code 400, message Bad request version ('À\x13À')
[03/Jan/2023 16:27:44] You're accessing the development server over HTTPS, but it only supports HTTP.`

**Comment by roborobs1023** [comment]
Yep issue still a problem.

**Comment by arshadkhan515** [comment]
> Can confirm as well that the 1.9.0 version is indeed bugged and downgrading as per @ManuLpz4 solved it for me as well.
yes brother

**Comment by ARSHADKHAN615** [comment]
> Can confirm as well that the 1.9.0 version is indeed bugged and downgrading as per @ManuLpz4 solved it for me as well.

yes brother

**Comment by Shinshi1** [comment]
Same here, but the downgrading suggested by @ManuLpz4  solved the problem for me.

**Comment by estruyf** [comment]
Thank you for opening this issue @franklin-vidal and all for verifying.

Our team is working to check what is going on and how to get it fixed.

**Comment by estruyf** [comment]
We have just released version `1.9.2` which includes a fix for this issue. Once you've updated to the latest version, you should be able to call your localhost services again.
