### ISSUE TITLE
[Bug]:  I don't know why I no Request snippet option?

### ISSUE THREAD

**Issue by lake05** [RapidAPI/feedback#83]
### What happened?

![image](https://user-images.githubusercontent.com/85690907/209905838-e0e822d1-75c8-4876-ae54-8e34972b26fd.png)

### Steps to reproduce?

can't select request  snippet

### VS Code version

1.74.2

### Extension version

1.9.0

**Comment by Giuseppe-Dicosmo** [comment]
I have the same problem as you

**Comment by Giuseppe-Dicosmo** [comment]
I have the same problem as you

**Comment by Giuseppe-Dicosmo** [comment]
I have the same problem as you

**Comment by alexle-developer** [comment]
I have the exact same problem with RapidAPI Client that does not show options in the Request snippet dropdown and also I cannot generate the Typescript interface.

- VS Code: 1.74.2
- RapidAPI Client Extension: 1.9.0 (installed from VS Code)

**Comment by Utsav1296** [comment]
Even i'm facing the exact same problem, using the same version of VS Code: 1.74.2 as well as the RapidApi Client extension: 1.9.0 (installed from VS Code).
No option for request snippet as it shows a blank dropdown also it is unable to generate typescript code.

**Comment by ramprasad-selvam** [comment]
Metoo having the same issue...

**Comment by BillPettigrew** [comment]
Driving me crazy. Thought I was the only one with this issue

**Comment by delight** [comment]
You can install the previous version (1.8.2) to make it work again.

**Comment by ARSHADKHAN615** [comment]
same here, any news about this?

**Comment by darwin1989-bit** [comment]
> You can install the previous version (1.8.2) to make it work again.

thanks if it worked by downloading the version, I will update it once the errors are corrected.

**Comment by ststimac** [comment]
Thanks for reporting everyone, I'll get an engineer to look at this ASAP. 

- Stephanie, PM for DevTools

**Comment by ststimac** [comment]
Hi everyone, this issue was fixed and deployed today. Please let us know if you encounter any other issues with the extension.
