### ISSUE TITLE
[feedback]: 

### ISSUE THREAD

**Issue by enriquecoblaz** [RapidAPI/feedback#84]
### What would you like to tell us?

The RapidApi client in vscode does not work for me. Edit: Only the current version

**Comment by francocarballar** [comment]
The current version doesn't work for me either.

**Comment by estruyf** [comment]
@enriquecoblaz @francocarballar can you let us know if the latest version is working for you? We released one yesterday.

If not, can you let us know what exactly is not working so we have more information to see where things might be failing?

**Comment by estruyf** [comment]
Closing the issue. Feel free to open it again if it still occurs.
