### ISSUE TITLE
[Bug]: The extension doesn't respect color theme at all

### ISSUE THREAD

**Issue by klesh** [RapidAPI/feedback#89]
### What happened?

I tried multiple  dark themes, with no luck, every single one of them showed me this white background:

![image](https://user-images.githubusercontent.com/61080/212632771-56aa45e0-c1b8-4189-9deb-f34fe1d85a83.png)

### Steps to reproduce?

Windows 11 22H2

Themes that I tried:
Vscode Dark
Solarized Dark
Shades of purple
Gruvbox Dark
and many others

### VS Code version

1.74.3

### Extension version

v1.9.2

**Comment by ttsirkia** [comment]
Stange. I have dark One Monokai in Windows 10 and it works just fine.
![kuva](https://user-images.githubusercontent.com/2797729/213472138-bf2f4a47-fa37-40b8-968a-e0290e1f12bc.png)

**Comment by klesh** [comment]
I switched to Thunder Client and it worked fine. 😂
