### ISSUE TITLE
[Bug]: cookies doesnt work on my vscode

### ISSUE THREAD

**Issue by diecodev** [RapidAPI/feedback#93]
### What happened?

I have vscode extension installed, in the Sessions apart I see the cookies that my api send. When i send a get request to some api endpoint and in that endpoint i try to read the cookies i send before, they dont appear:

### Steps to reproduce?

Create a deno server with oak middleware.

### step 1
I send a post http request to register
![create cookie](https://user-images.githubusercontent.com/51871681/214206785-c1733fd2-254d-4f54-9a76-ebee4da67f27.png)

### step 2
I verify my cookies are cached
![cookies sessions](https://user-images.githubusercontent.com/51871681/214206780-dbd264fd-f434-499d-9e7a-6657e185246e.png)

### step 3
I make a get http request just to get the user data but i verify if the cookie exists and if it's valid, but, the cookies are not sent
![cookist does not send](https://user-images.githubusercontent.com/51871681/214206783-2af806d8-d825-4025-a549-15ce485495df.png)

### step 4
My server log:
![server log](https://user-images.githubusercontent.com/51871681/214206786-6875fdab-63eb-4cbc-8e3f-de86dc5e8497.png)

### VS Code version

1.74.3

### Extension version

1.9.3

**Comment by estruyf** [comment]
Thanks, @diecodev, this will get fixed in the upcoming release. It seems that there was in issue in the `touch-cookie` dependency which got fixed: https://github.com/salesforce/tough-cookie/pull/253

**Comment by estruyf** [comment]
We just released version 1.10.0 in which this issue got fixed. Thank you @diecodev for reporting this! 🙏
