### ISSUE TITLE
[Bug]: Generating JS file with TypeScript interface

### ISSUE THREAD

**Issue by msaaddev** [RapidAPI/feedback#97]
### What happened?

When I tried to generate a TypeScript interface for my API response, the extension generated a JavaScript file and put the interface in it.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/44341551/218760394-cac24306-f04a-446d-ae87-6c6fc75b27ae.png">

### Steps to reproduce?

1. Call an API inside RapidAPI Client
2. Click on <> button to generate TypeScript interface

### VS Code version

1.75.1

### Extension version

v1.9.3

**Comment by estruyf** [comment]
We'll look into the issue, and probably the language is not configured correctly for some reason. The file itself is not yet saved, so it can also be that VSCode overrides the language to a preferred language.

Thanks @msaaddev for reporting this.

**Comment by estruyf** [comment]
This is fixed in version `1.10.0`.
