### ISSUE TITLE
[Bug]: Interface error

### ISSUE THREAD

**Issue by yasielhp** [RapidAPI/feedback#98]
### What happened?

<img width="2048" alt="Screenshot 2023-02-24 at 11 55 43" src="https://user-images.githubusercontent.com/8173924/221173660-047eaf81-9123-4eef-b11a-79210c94c60d.png">

### Steps to reproduce?

I have made a GET request with wrong parameters and this error appeared and I don't know how to remove it.

### VS Code version

 1.75.1 

### Extension version

v1.9.3

**Comment by yasielhp** [comment]
["ERROR" - 2023-02-24T12:17:58.989Z - v1.9.3] 
  Panel webview: {"error":"URIError: URI malformed","eventId":"2774d0e095f74bc483c2ccb20b9e6d13"}

**Comment by estruyf** [comment]
Hi @yasielhp do you happen to know what kind of wrong parameters you tried to use?

**Comment by estruyf** [comment]
We just released version 1.10.0 in which this issue got fixed. Thank you @yasielhp for reporting this! 🙏
