### ISSUE TITLE
[Bug]: Cookies not sent automatically 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [RapidAPI/feedback#99]
### What happened?

I though I was making a mistake while implementing my `express-session` code.

After many hours searching in Google, trying different solutions, I finally had a hunch, and switched to `Thunder Client` VSCode extension. And it worked right away! 

So, I uninstalled Rapid API Client extension, reloaded VSCode, and nothing changes.

I have to set the Cookie header manually, even though the `Automatically Send Cookies` and `Store Received Cookies` options are enabled.

Checked if there was an update pending to no avail.

Any tips will be appreciated. Thanks!

### Steps to reproduce?

Make a GET request to an endpoint that has the session injected after a login POST request with `express-session` package.
req.session.user is undefined.

In order to get the user, I have to set the Cookie header manually, with the key "session" and the value returned by the login request.

### VS Code version

1.72.2

### Extension version

1.9.3

**Comment by estruyf** [comment]
Hi @angelhdzmultimedia would you be able to provide a bit more information?

The `store received cookies` option works when you perform a request to an endpoint that returns the `set-cookie` header. When enabled, the cookie will be stored in your session. 

![Xnapper-2023-03-16-11 56 47](https://user-images.githubusercontent.com/2900833/225596535-eed9ef31-7aff-4c7c-8859-46a7281acbb1.png)

With the `Automatically Send Cookies` enabled, the cookies will automatically be sent upon request.

![Xnapper-2023-03-16-11 59 04](https://user-images.githubusercontent.com/2900833/225597140-a71f30af-4421-49e5-8a67-605d0f54f6e1.png)

**Questions**

- Can you check if you get a `set-cookie` header from the response?
- Can you check if the cookie got added to the sessions?

**Comment by angelhdzmultimedia** [comment]
> Hi @angelhdzmultimedia would you be able to provide a bit more information?
> 
> The `store received cookies` option works when you perform a request to an endpoint that returns the `set-cookie` header. When enabled, the cookie will be stored in your session.
> 
> ![Xnapper-2023-03-16-11 56 47](https://user-images.githubusercontent.com/2900833/225596535-eed9ef31-7aff-4c7c-8859-46a7281acbb1.png)
> 
> With the `Automatically Send Cookies` enabled, the cookies will automatically be sent upon request.
> 
> ![Xnapper-2023-03-16-11 59 04](https://user-images.githubusercontent.com/2900833/225597140-a71f30af-4421-49e5-8a67-605d0f54f6e1.png)
> 
> **Questions**
> 
> * Can you check if you get a `set-cookie` header from the response?
> * Can you check if the cookie got added to the sessions?

Thank you so much for your kind response!

Yes, set-cookie is present, with the connect:sid token from express-session when I make the POST request to `/api/auth/login`.

![image](https://user-images.githubusercontent.com/10191085/225711745-b219e872-e31d-4b44-8983-06387f7b470a.png)

But when I make a GET request to `/api/auth/user`, I get a 403 Session not valid, that could mean Rapid API didn't send the cookie, even though the cookie was present in `login `request, that should have been saved by Rapid API and send automatically in the `user` request.

So, of course, with everything being the same, the MongoDB database, the NestJS server, everything the same for both tests, 
I switched back again to Thunder Client, and it is sending the cookie automatically, because the request to `/api/auth/user` is successful and the response sends me the user ID instead of throwing the 403 error.

Auth Controller:

![image](https://user-images.githubusercontent.com/10191085/225712428-a2f6f6a7-8089-448b-ac50-8847ede6348c.png)

Auth Service > login:

![image](https://user-images.githubusercontent.com/10191085/225712593-54c387b0-5c63-4e61-b47b-6b5835b95a84.png)

My apologies if I'm missing something or messing up somewhere. I'm new to this world of session and tokens, and of course, new to Rapid API VSCode extension.

My NestJS server app is working in the browser and with ThunderClient. Both TC and the browser are sending the cookie automatically. I have set `credentials: true` in my API request in the client (Nuxt), and before sending this comment, 
I tried explicitly adding the `Access-Control-Allow-Credentials​: true` headers in my `/api/auth/user` request to see if that was what was missing without avail.

Appreciate your time and effort.

Wishing you health, peace, and success.

**Comment by estruyf** [comment]
Would you be able to show what is stored in the sessions as that is the part that is missing?

**Comment by angelhdzmultimedia** [comment]
> Would you be able to show what is stored in the sessions as that is the part that is missing?

Yes. In the browser and with Thunder Client, the `/api/auth/user` GET request returns what's saved in the session.
I used to store the whole user data object, but this is not a good practice apparently, so now I'm storing the user's ID, and with that ID I search the user in the MongoDB database and return it instead.

So yes, with TC I'm getting the user's ID, but with RA, I'm getting error 403, that means the session.user is undefined.

Let me send you a video hold on please.

**Comment by angelhdzmultimedia** [comment]
### Video of the issue: 

https://www.youtube.com/watch?v=C7tu665B-dY
![image](https://user-images.githubusercontent.com/10191085/225774269-e4991f3d-ebe8-44fa-b446-dc20c3e489d5.png)

**Comment by estruyf** [comment]
I wanted you to show session view.

![Xnapper-2023-03-17-14 46 17](https://user-images.githubusercontent.com/2900833/225922899-5430b79a-cd76-47a8-8337-52e00c8cdf08.png)

But I now also understand the issue. This problem will be fixed in the upcoming release. It was an issue in the `tough-cookie` dependency where localhost was not valid to add cookies.

**Comment by angelhdzmultimedia** [comment]
> I wanted you to show session view.
> 
> ![Xnapper-2023-03-17-14 46 17](https://user-images.githubusercontent.com/2900833/225922899-5430b79a-cd76-47a8-8337-52e00c8cdf08.png)
> 
> But I now also understand the issue. This problem will be fixed in the upcoming release. It was an issue in the `tough-cookie` dependency where localhost was not valid to add cookies.

Phew! Relieving news! And my apologies for the confusion. Here's the session menu for the record.

![image](https://user-images.githubusercontent.com/10191085/225978839-4d63ae5c-8c23-4874-a223-82585dc32322.png)

Should I close the issue? Or the maintainers will close it when the fix comes in?

**Comment by estruyf** [comment]
Will close it once the release is out. Should be done later today.

**Comment by estruyf** [comment]
The fix was released last week within `1.10.0`

**Comment by angelhdzmultimedia** [comment]
> The fix was released last week within `1.10.0`

Thank you so much! Now that I managed to use express-session in Nuxt 3, I will be using Rapid this week for all my tests!
I have a video on my YouTube channel trying out Rapid, and I participated in a Spanish conference recently, where if I'm not mistaken, Rapid was sponsor! (MiduFest).

**Comment by estruyf** [comment]
It seems we are. That is great to hear! Feel free to share the video to us after so that we can work with the DevRel team to reshare it.

**Comment by angelhdzmultimedia** [comment]
Cookies not sent automatically again!

Today I built a new app. Session is working in Postman, ThunderClient, and in Rapid API, the connect.sid cookie is stored (I can see it in Sessions tab), but is not sent automatically when I make the GET request to http://localhost:5000/auth/profile.

![image](https://github.com/RapidAPI/feedback/assets/10191085/7b4554a5-0373-4594-b979-e0a505cbe2aa)

![image](https://github.com/RapidAPI/feedback/assets/10191085/852c1f27-f330-4b35-8e6e-369e0c6b2408)

**Comment by montanaflynn** [comment]
Same issue with me, cookies are not being saved or sent.
